### ISSUE TITLE
Update Log Viewer to match ext standards

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/react-log-viewer#21]
We'd like to check all extensions to try to update dependencies, node versions, etc. to ensure that our support is consistent across PF and our extensions.

- React 18 support, node 18
- Webpack 5 (and general dependencies update)
- A11y (at least testing on each PR)
- Linting - bump to version 8

**Comment by wise-king-sullyman** [comment]
After closing #25 this extension is:

- on React 18
- supporting Node 18
- using Webpack 5
- a11y testing PRs
- using Eslint 8
