### ISSUE TITLE
Remove deprecated PatternFly components

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/react-log-viewer#46]
Components that were deprecated as part of the v5 PatternFly release are still in use.

[Those deprecated components](https://github.com/search?q=repo%3Apatternfly%2Freact-log-viewer%20%2Fdeprecated&type=code) should be replaced with the non-deprecated components or approaches PatternFly now recommends.

**Comment by jessiehuff** [comment]
https://github.com/patternfly/react-log-viewer/pull/49
