### ISSUE TITLE
Design review / updates for react log viewer

### ISSUE THREAD

**Issue by dlabaj** [patternfly/react-log-viewer#63]
The latest version of the first alpha was merged in this PR https://github.com/patternfly/react-log-viewer/pull/60 It does require additional design review.

- [x] Alpha has been reviewed by design
- [ ] Updates have been made to the UI per design review
- [ ] Code reivew and tested

Link to surge site to review:

 [Surge preview](https://neat-voyage.surge.sh/extensions/log-viewer)

**Comment by andrew-ronaldson** [comment]
![Screenshot 2024-04-25 at 10 33 14 AM](https://github.com/patternfly/react-log-viewer/assets/28658548/90c56517-bb5f-4a73-b8d1-6158d00e92ef)
Sorry one other thing is the pause button should have a `.pf-m-start` class to add the xs spacer between the icon and the text in the button.

**Comment by nicolethoen** [comment]
Closed by #64
