### ISSUE TITLE
PF6 - view full screen feature in react demo is glitchy

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/react-log-viewer#67]
when closing full page mode, the log disappears

the toolbar on the full page mode has a black/missing background

**Comment by wise-king-sullyman** [comment]
Moving to the backlog as these are not v6 specific issues, the same problems appear on main https://www.patternfly.org/extensions/log-viewer/react-demos

**Comment by HarpalSingh7395** [comment]
@wise-king-sullyman Is there an opportunity for me to contribute to fixing this issue?

**Comment by nicolethoen** [comment]
@HarpalSingh7395 you are welcome to contribute a fix! Please keep us updated as to your progress.
Or feel free to reach out if you have any questions!

**Comment by HarpalSingh7395** [comment]
@nicolethoen Thank you for the opportunity! I'll get started on the fix and keep you updated on my progress. If I run into any questions, I'll be sure to reach out.

**Comment by HarpalSingh7395** [comment]
@nicolethoen I have created a [pull request](https://github.com/patternfly/react-log-viewer/pull/72) that addresses the bug. Please let me know if there are any additional changes or improvements needed.

**Comment by HarpalSingh7395** [comment]
@nicolethoen I fixed the linter issue.

**Comment by HarpalSingh7395** [comment]
@nicolethoen I fixed the linter issue.
